export const SET_ALL_VARIATIONS = 'SET_ALL_VARIATIONS';
export const INCREMENT_ACTIVE_COMBINATION_NUMBER = 'INCREMENT_ACTIVE_COMBINATION_NUMBER';
export const DECREMENT_ACTIVE_COMBINATION_NUMBER = 'DECREMENT_ACTIVE_COMBINATION_NUMBER';
